In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r'C:\Users\idinn\Downloads\Copy of Class Time Table for 2020 Spring Semester_Version II - Slot System.csv')

In [6]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Forenoon Slots,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,08:00 - 08:55,09:00 - 09:55,10:00 - 10:55,11:00 - 11:55,12:00 - 12:55,13:00 - 13:55,14:00 - 14:55,15:00 - 15:55,16:00 - 16:55,17:00 - 17:55
3,Mon,G,B,A,J,K,Lunch,NaN,NaN,NaN,I
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Tue,NaN,F,C,B,E,NaN,NaN,NaN,NaN,I
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Wed,G,F,C,D,E,NaN,NaN,NaN,NaN,H
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Thu,G,F,A,J,K,NaN,D,NaN,NaN,C
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Fri,NaN,B,A,D,E,NaN,NaN,NaN,NaN,J
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Sat,NaN,NaN,NaN,I,K,NaN,H,H,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Afternoon Slots,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,08:00 - 08:55,09:00 - 09:55,10:00 - 10:55,11:00 - 11:55,12:00 - 12:55,13:00 - 13:55,14:00 - 14:55,15:00 - 15:55,16:00 - 16:55,17:00 - 17:55
20,Mon,NaN,NaN,NaN,NaN,Lunch,W,Z,U,X,Y
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Tue,NaN,NaN,NaN,NaN,NaN,Z,V,S,U,X
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Wed,NaN,NaN,NaN,T,NaN,V,Y,S,X,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Thu,NaN,NaN,NaN,NaN,NaN,Z,T,W,S,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Fri,NaN,NaN,NaN,T,NaN,U,V,Y,W,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Note: Schedule of Laboratories will be prepare...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
t = df[df.columns[0]].notnull()
for i in range(1,len(df.columns)):
    t = t | df[df.columns[i]].notnull()

In [8]:
df[t]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Forenoon Slots,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,08:00 - 08:55,09:00 - 09:55,10:00 - 10:55,11:00 - 11:55,12:00 - 12:55,13:00 - 13:55,14:00 - 14:55,15:00 - 15:55,16:00 - 16:55,17:00 - 17:55
3,Mon,G,B,A,J,K,Lunch,NaN,NaN,NaN,I
5,Tue,NaN,F,C,B,E,NaN,NaN,NaN,NaN,I
7,Wed,G,F,C,D,E,NaN,NaN,NaN,NaN,H
9,Thu,G,F,A,J,K,NaN,D,NaN,NaN,C
11,Fri,NaN,B,A,D,E,NaN,NaN,NaN,NaN,J
13,Sat,NaN,NaN,NaN,I,K,NaN,H,H,NaN,NaN
17,Afternoon Slots,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,08:00 - 08:55,09:00 - 09:55,10:00 - 10:55,11:00 - 11:55,12:00 - 12:55,13:00 - 13:55,14:00 - 14:55,15:00 - 15:55,16:00 - 16:55,17:00 - 17:55
20,Mon,NaN,NaN,NaN,NaN,Lunch,W,Z,U,X,Y
22,Tue,NaN,NaN,NaN,NaN,NaN,Z,V,S,U,X
24,Wed,NaN,NaN,NaN,T,NaN,V,Y,S,X,NaN
26,Thu,NaN,NaN,NaN,NaN,NaN,Z,T,W,S,NaN
28,Fri,NaN,NaN,NaN,T,NaN,U,V,Y,W,NaN
31,Note: Schedule of Laboratories will be prepare...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
d = {}

In [10]:
from collections import namedtuple

In [11]:
interval = namedtuple("interval",["day","time"])

In [12]:
a  = interval(day="wednesday", time="10-11")

In [13]:
a.day

'wednesday'

In [14]:
d["A"]

KeyError: 'A'

In [ ]:
[(d),
,
]

In [ ]:
d :{
    "char": [intevals,,,]
}

In [ ]:
df = pd.read_csv(r'C:\Users\idinn\Downloads\Copy of Class Time Table for 2020 Spring Semester_Version II - ')